In [3]:
import pandas as pd

La libreria numpy nos permite crear vectores

In [4]:
import numpy  as np

conos = pd.DataFrame({
    'Sabor': np.array(['mora', 'vainilla', 'chocolate' ])
})

In [2]:
import numpy as np

words = np.array(['nombre', 'Pronombres', 'verbo', 'adverbio', 'adjetivo'])
words[4]

np.str_('adjetivo')

words[Pi:Pf:I]
Pi = posicion inicial
Pf = posicion final
I = incremento

In [21]:
words[ : :-1]

array(['adjetivo', 'adverbio', 'verbo', 'Pronombres', 'nombre'],
      dtype='<U10')

In [3]:
numbers = np.array([1, 3, 5.3])
numbers

array([1. , 3. , 5.3])

In [24]:
numbers.sum()

np.float64(9.3)

In [26]:
numbers.size

3

In [28]:
numbers.mean()

np.float64(3.1)

In [34]:
np.count_nonzero(numbers)

3

In [37]:
np.round(numbers)

array([1., 3., 6.])

In [58]:
np.cumsum(numbers)

array([1., 3., 8.])

In [57]:
numbers[2] = np.round(numbers[2])

numbers

array([1., 2., 5.])

In [ ]:
np.sort(numbers)

array([-5.3, -3. , -1. ])